apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: local-storage-exporter-servicemonitor
spec:
  selector:
    matchLabels:
      app: local-storage-exporter
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    any: true