{{ include "validate.requiredValues" . }}
{{ $metricsPort := include "validate.metricsPort" . }}
---
{{ if .Values.daemonSet.enable -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-local-storage-exporter-daemonset
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-local-storage-exporter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-local-storage-exporter
    spec:        
      serviceAccountName: {{ .Release.Name }}-local-storage-exporter-serviceaccount
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .Values.daemonSet.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.daemonSet.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.daemonSet.tolerations }}
      tolerations:
        {{- toYaml .Values.daemonSet.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.excludeNodes }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      {{- toYaml .Values.excludeNodes | nindent 22 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-local-storage-exporter
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{ range .Values.storagePaths -}}
          - name: "node-data-{{ include "urlsafeB64enc" . | lower }}"
            mountPath: "/volumes/{{ include "urlsafeB64enc" . | lower }}" # Where it appears in container
            readOnly: true
          {{ end -}}
          ports:
            - containerPort: {{ $metricsPort }}
              name: metrics
          env:
            - name: STORAGE_CLASS_NAMES
              value: {{join "," .Values.storageClassNames }}
            - name: METRICS_PORT
              value: {{ quote $metricsPort }}
            - name: UPDATE_INTERVAL
              value: {{ quote .Values.updateInterval }}
            - name: LOGLEVEL
              value: {{ .Values.logLevel | upper | quote }}
      volumes:
      {{ range .Values.storagePaths -}}
      - name: "node-data-{{ include "urlsafeB64enc" . | lower }}"
        hostPath:
          path: {{ . }}
          type: Directory # Ensures directory exists
      {{ end -}}
{{ end -}}