{{ include "validate.requiredValues" . }}
{{ $metricsPort := include "validate.metricsPort" . }}
{{ include "validate.imagePullPolicy" . }}
{{ include "validate.imagePullSecrets" . }}
---
{{ if .Values.daemonSet.enable -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-local-storage-exporter-daemonset
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-local-storage-exporter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-local-storage-exporter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists        
          effect: NoSchedule
        - key: node-role.kubernetes.io/master

      serviceAccountName: {{ .Release.Name }}-local-storage-exporter-serviceaccount
      {{ if .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{ range .Values.imagePullSecrets -}}
        - name: {{ .name }}
      {{ end -}}
      {{ end -}}
      containers:
        - name: {{ .Release.Name }}-local-storage-exporter
          {{ if .Values.repository -}}
          image: {{ .Values.repository }}/local-storage-exporter:{{ .Values.tag }}
          {{ else -}}
          image: local-storage-exporter:{{ .Values.tag }}
          {{ end -}}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: node-data
              mountPath: /volumes # Where it appears in container
              readOnly: true
          ports:
            - containerPort: {{ $metricsPort }}
              name: metrics
          env:
            - name: STORAGE_CLASS_NAMES
              value: {{join "," .Values.storageClassNames }}
            - name: METRICS_PORT
              value: {{ quote $metricsPort }}
            - name: UPDATE_INTERVAL
              value: {{ quote .Values.updateInterval }}
      volumes:
        - name: node-data
          hostPath:
            path: {{ .Values.storagePath }}
            type: Directory # Ensures directory exists
{{ end -}}